### ISSUE TITLE
PickerButton

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#202]
![Screen Shot 2021-06-29 at 10 08 44 AM](https://user-images.githubusercontent.com/176720/123812360-0390ac00-d8c2-11eb-9ca7-4a91e05ff90d.png)

**Comment by PascalPrecht** [comment]
Adding some more context here. This is what the flow looks like (source: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=2431%3A28468):

<img width="663" alt="Screenshot 2021-07-05 at 16 52 43" src="https://user-images.githubusercontent.com/445106/124489576-71047700-ddb1-11eb-9747-e6d59c10eddd.png">


This depends on #106

**Comment by alexandraB99** [comment]
@PascalPrecht would [ColorDialog](https://doc.qt.io/qt-5/qml-qtquick-dialogs-colordialog.html) be an option? It might open in a different window though
![colorPicker.png](https://images.zenhubusercontent.com/60e32e06eddded5b0a4e2749/7d83182b-ee2a-41a1-bd02-c97c772e5b12)

**Comment by PascalPrecht** [comment]
@alexandraB99 I think it's fine as an intermediary step, if that helps us landing a **functional** component (across platforms)

**Comment by John-44** [comment]
@alexandraB99 as intermediary step fine, but after this intermediary step is completed lets try to get some form of colour picker integrated into the dialogue as per the design.
