### ISSUE TITLE
Add image and identicon support to `StatusPopupMenu`

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/StatusQ#263]
`StatusPopupMenu` and `StatusMenuItem` support configuring an optional `icon` like so:

```qml
StatusPopupMenu {
    StatusMenuItem { 
        text: "One" 
        icon.name: "info"
    }

    StatusMenuSeparator {}

    StatusMenuItem { 
        text: "Two"
        icon.name: "info"
    }
}
```

Or nested popup menus, parent menus have to define the icon for their child menus with a list of icons in the same order as they appear in the menu, e.g:

```qml
StatusPopupMenu {
    id: complexMenu
    subMenuItemIcons: ['info'] // <- the first item here maps to the first `StatusPopupMenu` in this menu
    StatusMenuItem { 
        text: "One" 
        icon.name: "info"
    }

    StatusMenuSeparator {}

    StatusMenuItem { 
        text: "Two"
        icon.name: "info"
    }

    StatusMenuItem { 
        text: "Three"
        icon.name: "info"
    }

    StatusPopupMenu { // <- which is this one
        title: "Four"
        StatusMenuItem { 
            text: "One"
            icon.name: "info"
        }
        StatusMenuItem { 
            text: "Three"
            icon.name: "info"
        }
    }
}
```

This issue is about adding support for `StatusImageSettings` as well, allowing consumers of this component to specify a custom image source.

<img src="https://cdn.discordapp.com/attachments/834501835175624735/864984696249122816/Screen_Shot_2021-07-14_at_5.40.08_PM.png">

This can probably be done by extending `StatusPopupMenu.subMenuItemIcons` to take `StatusImageSettings` objects instead. Or, to not introduce a breaking change, we can add a new `subMenuItemImages` property.

Similarly, `StatusMenuItem` needs to accept `StatusImageSettings` as well.

**Comment by iurimatias** [comment]
![Screen_Shot_2021-07-15_at_9.45.56_AM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/dc52f0a5-2a86-44ae-b72e-5a12c454e4fd)
