### ISSUE TITLE
Add RobotoMono-Regular font face

### ISSUE THREAD

**Issue by pinebit** [status-im/StatusQ#342]
This is needed for <code> tag as per our design.

**Comment by PascalPrecht** [comment]
So far, the mono font faced used in the designs was the `InterSatus` font, which you can find here https://github.com/status-im/StatusQ/tree/master/src/assets/fonts/InterStatus and is exposed in `Theme` via these properties: https://github.com/status-im/StatusQ/blob/master/src/StatusQ/Core/Theme/ThemePalette.qml#L18-L25

I assume this is not what you're looking for then?

**Comment by pinebit** [comment]
We do not need just "mono". We need exactly "Roboto Mono Regular", because it is used in our design (Figma) for code blocks.

**Comment by PascalPrecht** [comment]
Gotcha!

**Comment by simonricoo** [comment]
Can you point me where do you see RobotoMono-Regular please? @pinebit

**Comment by pinebit** [comment]
> Can you point me where do you see RobotoMono-Regular please? @pinebit

Sure!
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4170%3A20
![image](https://user-images.githubusercontent.com/6468078/131533784-68d58c87-6979-44a8-841f-1557f45f0b20.png)

**Comment by PascalPrecht** [comment]
Gonna add that to StatusQ assets

**Comment by pinebit** [comment]
I took the font from Google Fonts (otf).
