### ISSUE TITLE
Provide hook for timestamp formatting function  in `StatusSearchPopup`

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/StatusQ#363]
The search results in `StatusSearchPopup` rely on a `model.time` property which is a timestamp that needs proper formatting based on the configure locale of the application.

Since i18n isn't StatusQ's concern, we can't hard code the formatting into the component.
That's why we need a new API so consumers of this component can provide a function that is called to format the timestamp.

Maybe something long these lines:

```
StatusSearchPopup {
  ...
  timestampFormattingFn: function (ts) {
    // return formatted timestamp
  }
}
```

In the long term, we should probably reconsider whether it makes sense to have the complete search popup component in StatusQ, or if it makes more sense to only provide the building blocks so apps like Status Desktop can build a search popup component.

This would give consumers more control over how data is passed to search results.

**Comment by saledjenic** [comment]
@PascalPrecht for a long term we may consider an option to expose transaltor to the nim part and handle this timestamp conversion there, that way qml would receive just a value which it needs for displaying.
