### ISSUE TITLE
Add support for `asyncValidators` in `StatusInput`

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/StatusQ#395]
Something that needs to be explored. There are a bunch of use cases for async validators. In Status Desktop specifically, there's a case where an input lets users enter ENS names. Those names need to successfully resolve. If they don't they should be considered invalid.

We need to look into how this can be done in a nice way, but from a usage point of view, this should look similar to using synchronous validators:

```qml
StatusInput {
  ...
  validators: [...]
  asyncValidators: [...]
}
```

We probably need to leverage `Connections` here. Need to play around with this to see how this can work.
We definitely need to introduce a new `pending` state.

One requirement that is known for sure: Asynchronous validators are only executed when synchronous validation was successful.

**Comment by emizzle** [comment]
Agreed, asynchronous validators will likely need to wait for synchronous validators to validate successfully, but they may also need a condition that must resolve to true before it is fired.

```qml
StatusInput {
  id: inp
  ...
  validators: [
    StatusAddressOrEnsValidator { ... }
  ],
  asyncValidators: [
    StatusAsyncEnsValidator {
      fireWhen: Utils.isEns(inp.text)
    }
  ]
}
```

It means the ENS regex will fire twice, but that's cheaper than firing the async call.

**Comment by emizzle** [comment]
> We probably need to leverage Connections here. Need to play around with this to see how this can work.

I can definitely help out in this regard. I'd highly recommend using `Result` types that bubble up and make their way back to the QML, as it's a guaranteed way to know if the request/command was successful and if successful, the value result, or if failure, the error. Here is an example of it in a PR I recently introduced: https://github.com/status-im/status-desktop/pull/3425/files#diff-8e205b46db644f10fe491a1a39b1947a648c2d5403eb12cf0bd92e34ceea5bfcR193-R234. Notice that the error coming back is actually a direct enum mapping in qml to a nim error enum, which means it serves to translate lower level error messaging to user-friendly error messaging (or not showing an error at all). In other words, this completely async methodology does not block the UI thread and allows us to show values or errors or nothing at all, depending on what is needed for the UI.
