### ISSUE TITLE
Sandbox app can't be built on linux

### ISSUE THREAD

**Issue by richard-ramos** [status-im/StatusQ#413]
```
make: *** No rule to make target 'clean'.  Stop.
Project ERROR: Could not resolve SDK Path for 'macosx' using --show-sdk-path
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by Khushboo-dev-cpp** [comment]
./sandbox/spellchecker.cpp:3:10: fatal error: hunspell.hxx: No such file or directory
3 | #include "hunspell.hxx"
| ^~~~~~

Need to add checks OS checks to resolve these errors

I get this error when building

**Comment by PascalPrecht** [comment]
Should be fixed with https://github.com/status-im/StatusQ/commit/dce45c2ff3c49ceb8072a10973f126be7d21717e can you verify @richard-ramos ?

**Comment by PascalPrecht** [comment]
This seems to be still an issue.

@Khushboo-dev-cpp anything in particular that needs to be done to have this work (given your fix commit)?
