### ISSUE TITLE
`StatusChatInfoButton` takes up entire available `width` again

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/StatusQ#432]
This is an issue that was fixed in the passed. Here's what it looks like now (notice the width of the button via hover effect):
<img width="313" alt="Screenshot 2021-10-04 at 14 07 30" src="https://user-images.githubusercontent.com/445106/135848862-beff8a47-1515-4a34-96f3-fe2ec6e2a140.png">
<img width="621" alt="Screenshot 2021-10-04 at 14 07 24" src="https://user-images.githubusercontent.com/445106/135848884-14b457b2-eb69-4d5f-881d-24fa179780f4.png">

This is what it should look like (only take as much space as needed):
<img width="359" alt="Screenshot 2021-10-04 at 14 07 51" src="https://user-images.githubusercontent.com/445106/135848927-cd0a3dc3-f212-484f-9e3d-f82f7f951e2a.png">

Looks like this broke in https://github.com/status-im/StatusQ/commit/d9da5bdc1d02e8224d4f4684ef257bff2efc2ac1 with the introduction of `StatusSelectableText`.

@Khushboo-dev-cpp do you think you can take a look and fix this?

**Comment by Khushboo-dev-cpp** [comment]
@PascalPrecht Yes for sure. Let me check, I did test in sandbox and it looked alright, but the hover needs fixing then

**Comment by PascalPrecht** [comment]
The hover works fine, but you can use it to visualise the `width` of the component.
The button shouldn't take more space than needed.
