### ISSUE TITLE
StatusRadioButton default label needs better contrast in darkmode

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/StatusQ#51]
This is what it looks like, given:

```
StatusRadioButton {
  text: "Label"
}
```
<img width="116" alt="Screenshot 2021-05-20 at 11 18 37" src="https://user-images.githubusercontent.com/445106/118962936-34e29780-b966-11eb-92eb-9a008508370b.png">

@simonricoo I'm not sure from the top of my head if there are actually places in the app where we use the default label of this component, still, it should come with a decent default text color.

Should we just pick something or do you have a stronger opinion on this?

**Comment by simonricoo** [comment]
Radio button is usually a part of the list item. However, there are places that radio button comes with the text label eg.
Profile-Notifications-Sound&Appearance-Play a sound when receiving a notification (https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1559%3A72)
<img width="1520" alt="Screen Shot 2021-05-20 at 12 31 42" src="https://user-images.githubusercontent.com/52249767/118964008-585a1200-b967-11eb-808f-c158128c04a8.png">
