### ISSUE TITLE
Implement `StatusMemberListItem`

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#515]
relevant spec: https://github.com/status-im/feature-specs/pull/42/files
relevant figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=932%3A284701

new member component that includes online/offline indicator, trust indictor, optional chat key, optional original username

![Screen Shot 2022-01-12 at 2 43 39 PM](https://user-images.githubusercontent.com/176720/149210621-d000b20b-f4f2-46bb-bae6-329aed98f993.png)

**Comment by PascalPrecht** [comment]
This can most likely be implemented using `StatusListItem` component.
