### ISSUE TITLE
Add support for color rings in `StatusSmartIdenticon`

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#517]
relevant spec: https://github.com/status-im/feature-specs/pull/42/files
relevant figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=1837%3A335128

32 colors in 5 segments of various lengths, please refer to spec for more details

![Screen Shot 2022-01-12 at 2 47 42 PM](https://user-images.githubusercontent.com/176720/149211130-9953317a-2e48-4e8d-8ace-cd1ef2f5a2db.png)

**Comment by iurimatias** [comment]
we should analyze if it makes sense to generate this on the fly in qml or if it should come from the backend

**Comment by PascalPrecht** [comment]
We already have `StatusSmartIdenticon` which could most likely be leveraged for that: https://github.com/status-im/StatusQ/blob/master/src/StatusQ/Components/StatusSmartIdenticon.qml

Given that the ring is derived from a users chatkey(?) we probably need to extend the component's API
