### ISSUE TITLE
setup new profile screen

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#519]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba⎜Desktop?node-id=1838%3A337543

![Screen Shot 2022-01-12 at 2 58 45 PM](https://user-images.githubusercontent.com/176720/149212866-9733d67a-61d6-4bc1-a52f-d535d1ce793a.png)

**Comment by PascalPrecht** [comment]
@iurimatias I don't think this belongs in here. We already have all the components needed to compose such a view. But this is **application view** that shouldn't be provided by StatusQ.
