### ISSUE TITLE
Text field component

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#520]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=2463%3A318271

should have
- character counter
- character limit
- placeholder text

![Screen Shot 2022-01-12 at 3 16 13 PM](https://user-images.githubusercontent.com/176720/149215086-d4bfaa64-dd19-4021-a4d9-399094904fc6.png)

**Comment by PascalPrecht** [comment]
`StatusInput` already does all of these things. So I'm gonna close this.

Only thing we might want to reiterate is whether we want to have a dedicated textarea component (or keep leveraging `StatusInput`'s `multiline` property): https://github.com/status-im/StatusQ/issues/236
