### ISSUE TITLE
Implement `StatusToastMessage` component

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#521]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=2090%3A252386
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=1838%3A360271
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=1939%3A218046

![Screen Shot 2022-01-12 at 3 19 20 PM](https://user-images.githubusercontent.com/176720/149215521-475e3e9f-8be2-4cc9-97c5-9ad6a513e6f3.png)

**Comment by PascalPrecht** [comment]
Needs API proposal
