### ISSUE TITLE
Implement `StatusWizardStepper` component

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#522]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=2459%3A328034

![Screen Shot 2022-01-12 at 3 22 32 PM](https://user-images.githubusercontent.com/176720/149215895-a65fdf5f-d2d4-465a-82f6-7a57af48e9ee.png)

**Comment by PascalPrecht** [comment]
Needs API proposal.
