### ISSUE TITLE
Introduce `StatusPinInput`

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#524]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=1621%3A367655

![Screen Shot 2022-01-12 at 3 29 36 PM](https://user-images.githubusercontent.com/176720/149216912-ec8aeb32-2b4b-45f1-9aba-d761c4ed4710.png)

**Comment by PascalPrecht** [comment]
I don't think we need to introduce that whole thing in StatusQ. This is also an **application view** that can be built using components. Application views shouldn't live in the component library...

What we **do** need however, is this pin input component. All the other components there already exist (Image, text, button, the rest is application specific logic).

Updating the issue accordingly...

**Comment by iurimatias** [comment]
I agree with @PascalPrecht
