### ISSUE TITLE
Implement `StatusTagSelector` component

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#526]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=391%3A100984

![Screen Shot 2022-01-12 at 4 08 52 PM](https://user-images.githubusercontent.com/176720/149221834-d928c535-f49c-48bd-8ea1-6b0e66ccb15c.png)

![Screen Shot 2022-01-12 at 4 08 17 PM](https://user-images.githubusercontent.com/176720/149221852-79e59731-18c7-4516-ae8b-04b24775b0ac.png)

**Comment by PascalPrecht** [comment]
Created https://github.com/status-im/StatusQ/issues/531 accordingly
