### ISSUE TITLE
Add `StatusPasswordStrengthIndicator`

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#528]
figma: https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=11%3A4921

![Screen Shot 2022-01-12 at 4 17 05 PM](https://user-images.githubusercontent.com/176720/149222759-30805172-b966-4400-86f3-688a208726c0.png)

**Comment by PascalPrecht** [comment]
This could be a variation, or implementation, of `StatusProgressBar` (which doesn't exist yet).

**Comment by PascalPrecht** [comment]
@noeliaSD I like where this is going!

```
property string text
property color barColor
property color backColor
```

I'd propose we do `fillColor` and `backgroundColor` instead. 

```
enum TypeStrength {
        VeryWeak, // 0
        Weak, // 1
        SoSo, // 2
        Good, // 3
        Great // 4
    }
```

Could we call this just `Strength` instead?

I don't think we need a `TypeLength`. The length, or rather `width` of the component is controlled by its context.

I think it's okay for it to have an `implicitWidth` but other than that, it should be just overridable using `anchors` or `width`.

WDYT?

**Comment by noeliaSD** [comment]
**Pending things to clarify:**
Color `#9EA85D` corresponding to `Good` state is not defined in [Design System file](https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A10) so maybe it should be modified or add another one into that file.

**Comment by noeliaSD** [comment]
@PascalPrecht I agree with the proposed name.
Regarding the `Length` property, I think it should be defined (maybe also with a different name for not creating confusion), so it's not the width of the component itself, but the length of the color bar that indicates whether the characters of the password are "length enough" or could have more characters.

**Comment by PascalPrecht** [comment]
> Color #9EA85D corresponding to Good state is not defined in Design System file so maybe it should be modified or add another one into that file.

Good catch. Either needs change in design or a new `miscColor`.

> it's not the width of the component itself, but the length of the color bar that indicates whether the characters of the password are "length enough" or could have more characters.

Ahh I understand now. So this means it's possible to have a super weak password but the bar still being fully filled? That doesn't sound right to me...  the way I look at it, is that the length of the bar represents the strength of the password, not the length of the password. A super long password that super weak, is still super weak. Showing a short "very weak" bar vs a long "very weak" bar doesn't make a difference here.

Have you discussed/verified this with design?

**Comment by noeliaSD** [comment]
> Ahh I understand now. So this means it's possible to have a super weak password but the bar still being fully filled? That doesn't sound right to me... the way I look at it, is that the length of the bar represents the strength of the password, not the length of the password. A super long password that is super weak, is still super weak. Showing a short "very weak" bar vs a long "very weak" bar doesn't make a difference here.

@PascalPrecht I understand what you mean. Maybe we should double-check it. It make sense.

I understood that behavior from the design file, for example here: 
![image](https://user-images.githubusercontent.com/97019400/149995075-1fe36977-98e6-4b46-95e7-fc359343d3ca.png)
What do you understand from this image?

**Comment by PascalPrecht** [comment]
> What do you understand from this image?

It could also be just a representation of what a full bar looks like (despite it being "very weak").
To be sure, we should clarify this with design. I could also be wrong, in which case your proposal makes sense.

We could then even give full progress bar control and let consumers set a value between lowest and highest, which would result in the bar to be filled accordingly (similar to how it's done in `StatusSlider`)

**Comment by noeliaSD** [comment]
After discussing it with John, the coloured bar length must be modified progressively when characters are introduced being 6 characters corresponding with the longest bar length. So, my proposal for the control is giving the consumer the flexibility of establishing the needed value and use the `property value` from base class for that propose (so no `length` property included). Sounds good @PascalPrecht ?

Regarding the new color `#9EA85D`, he agrees, as well, in adding a new misc colour and propose a parner colour for the dark mode, and check.

**Comment by PascalPrecht** [comment]
Sounds good to me! Thanks for clarifying this

> Regarding the new color #9EA85D, he agrees, as well, in adding a new misc colour and propose a parner colour for the dark mode, and check.

Cool, feel free to send a separate PR for this addition to `Status.Core.Theme` or do it as part of the PR that introduces this password strength component.

Looking forward to this!

**Comment by noeliaSD** [comment]
Great! Let's do it!

**Comment by noeliaSD** [comment]
New colour agreed `dark mode` is `#AFB551` . Both should be added into the [Design System file](https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A10) by @davholik but as it is planned a restructuration of the color system, no actions until then in terms of figma file.

**Comment by davholik** [comment]
> New colour agreed `dark mode` is `#AFB551` . Both should be added into the [Design System file](https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A10) by @davholik but as it is planned a restructuration of the color system, no actions until then in terms of figma file.

Just to explain in detail, we are planning a pretty severe rework of the color system, introducing a new naming convention, a new structure of the palettes, new tints, shades as well as opacity solutions. So at this stage, it wouldn't make much sense to just introduce a random "green" into the system. Just leave it as a raw hex value without any semantic definition and we will fix it all at once when the new structure is introduced.

**Comment by PascalPrecht** [comment]
> Just to explain in detail, we are planning a pretty severe rework of the color system, introducing a new naming convention, a new structure of the palettes, new tints, shades as well as opacity solutions. 

Where are the discussions around that? We've put a lot of thought into the current theming system so that it works across different themes and stays customizable. Why is a severe rework needed? This might have a massive impact on StatusQ and Status Desktop. Something we should avoid at this stage because we're already in a transitioning phase to move from legacy theming system + components to StatusQ theming system + components.

**Comment by PascalPrecht** [comment]
Fair enough! Thanks for keeping us in the loop
