### ISSUE TITLE
Add support for autocompletion in `StatusTagSelector`, move suggestions popup inside component

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/StatusQ#531]
As discussed in #526, we need to add support for autocompletion, so that users get suggestions of things to be tagged. It's already implemented outside of `StatusTagSelector` in the demo app and in Status Desktop. This issue is about adding the ability to render the suggestions popup inside the `StatusTagSelector`.
Feel free to put an API proposal here.

**Comment by alexandraB99** [comment]
What would be the specifications for autocompletion? How should that work? A more detailed description of what needs to implemented exactly would help, possibly also designs from all phases.

**Comment by alexandraB99** [comment]
Ain't 2&3 already done [here](https://github.com/status-im/StatusQ/pull/537)? (see first video)

**Comment by PascalPrecht** [comment]
@alexandraB99You're right! I didn't realize it had the popup already. It thought it would only work with that external list in the demo chat view.

Only thing that's left to do as part of this task here then, would be to fine-tune the suggestion items to be properly aligned. Based on the video, it seems the items aren't positioned correctly (compared to what's in figma)

**Comment by alexandraB99** [comment]
> @alexandraB99You're right! I didn't realize it had the popup already. It thought it would only work with that external list in the demo chat view.
> 
> Only thing that's left to do as part of this task here then, would be to fine-tune the suggestion items to be properly aligned. Based on the video, it seems the items aren't positioned correctly (compared to what's in figma)

@PascalPrecht fixed in https://github.com/status-im/StatusQ/pull/552. However is not specified what happens when the x position will make the popup to go off screen, so in this case I put it back to 0.

**Comment by PascalPrecht** [comment]
@alexandraB99 I think there was a misunderstanding.. I was referring to the suggestion items themselves not being in the proper position. For example, here's what it looks like in sandbox now:

<img width="226" alt="Screenshot 2022-02-09 at 08 15 43" src="https://user-images.githubusercontent.com/445106/153140457-d3162d03-d464-4698-b901-57c5efb32ca4.png">

Here's what it looks like in figma
<img width="393" alt="Screenshot 2022-02-09 at 08 17 36" src="https://user-images.githubusercontent.com/445106/153140672-699c50bb-38f1-4560-8e96-28e49a688f9f.png">


Notice how in the sandbox version the information in each individual item isn't vertically centered.
