### ISSUE TITLE
`StatusListItem` and `StatusMessageHeader` title text out of the expected boundaries

### ISSUE THREAD

**Issue by noeliaSD** [status-im/StatusQ#540]
In `statusListItemTitle` when the **anchors.right** property is set as **undefined** it comes out of the expected boundaries.

Here the code:
```anchors.right: !statusListItem.titleAsideText && !titleIconsRow.visible ? parent.right : undefined```

**I.e:** 
- This is the expected behavior when only title is set and wrapped correctly:

![image.png](https://images.zenhubusercontent.com/61d30b5bf02a007f97c90ad2/f3f17203-48ff-450b-bca8-0e145847f72f)

- This is the bug when `titleAsideText ` property is set (it also happens when `titleIconsRow `property is true):
![image.png](https://images.zenhubusercontent.com/61d30b5bf02a007f97c90ad2/8861b1fb-b939-4028-b62c-41ffc8c1b4d4)

**NOTE:** The same issue is in `StatusMessageHeader.qml` component.

**Comment by noeliaSD** [comment]
_Originally posted by @noeliaSD in https://github.com/status-im/StatusQ/pull/539#discussion_r791840349_

**Comment by MishkaRogachev** [comment]
Reproduced:
![image](https://user-images.githubusercontent.com/2522130/166663085-07760b7c-8543-440a-86ab-54e2adba9208.png)
