### ISSUE TITLE
New selector component

### ISSUE THREAD

**Issue by iurimatias** [status-im/StatusQ#563]
see designs

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=973%3A105672

Picker button

![Screen Shot 2022-02-26 at 1 22 06 PM](https://user-images.githubusercontent.com/176720/155854703-4f031b2e-6af6-4702-819e-f4e075c0c5ec.png)

Selector

![Screen Shot 2022-02-26 at 1 13 53 PM](https://user-images.githubusercontent.com/176720/155854637-1bf984c7-2708-4cea-9250-5d2801e24cd1.png)

**Comment by noeliaSD** [comment]
Add checkbox component to allow the component to select from checkbox or radio button selector.
