### ISSUE TITLE
StatusFlatRoundButton doesn't allow for icon size configuration

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/StatusQ#57]
As per design, there are components we call `StatusFlatRoundButton` that can hold an icon in two different variations:

Light & Dark
<img width="491" alt="Screenshot 2021-05-21 at 12 16 35" src="https://user-images.githubusercontent.com/445106/119122057-66269a80-ba2e-11eb-9760-26245be66698.png">
Hovered:
<img width="501" alt="Screenshot 2021-05-21 at 12 17 04" src="https://user-images.githubusercontent.com/445106/119122112-763e7a00-ba2e-11eb-8166-e933ab01b466.png">

The component comes with an `implicitHeight/Width` of `44` and calculates its icon size based on that value, minus `20` which doesn't really work well.

We need a way to set the height/width of the icon independently of the size of the over all button (icon sizes may vary).

Two options I see here:

1) We expose the `StatusIcon` in use via `alias`, giving full control to the consumer

```
StatusFlatRoundButton {
  icon.name: "info"
  icon.width: 22
  icon.height 22
}
```

^ at the moment this doesn't work because `icon` isn't actually object but maps to `StatusIcon.icon`. One of the reasons we've used QML's built-in `RoundButton` was because it exposes an entire `icon` object already with `name`, `source`, `width` and `height` properties.

With the latest implementation of this component we've kinda lost all of that because we've reimplemented it with a `Rectangle`.

2) The design so far only uses a size of `32` for this kind of component. Unfortunately we can't hardcode `implicitWidth: 32` and `implicitHeight: 32` and then use `width` and `height` for icon sizes.. so the other option would be to introduce new properties accordingly:

```
StatusFlatRoundButton {
  icon: "info"
  iconWidth: 22
  iconHeight 22
}
```

@borismelnik thoughts?

**Comment by borismelnik** [comment]
> As per design, there are components we call `StatusFlatRoundButton` that can hold an icon in two different variations:
> 
> Light & Dark
> <img alt="Screenshot 2021-05-21 at 12 16 35" width="491" src="https://user-images.githubusercontent.com/445106/119122057-66269a80-ba2e-11eb-9760-26245be66698.png">
> Hovered:
> <img alt="Screenshot 2021-05-21 at 12 17 04" width="501" src="https://user-images.githubusercontent.com/445106/119122112-763e7a00-ba2e-11eb-8166-e933ab01b466.png">
> 
> The component comes with an `implicitHeight/Width` of `44` and calculates its icon size based on that value, minus `20` which doesn't really work well.
> 
> We need a way to set the height/width of the icon independently of the size of the over all button (icon sizes may vary).
> 
> Two options I see here:
> 
> 1. We expose the `StatusIcon` in use via `alias`, giving full control to the consumer
> 
> ```
> StatusFlatRoundButton {
>   icon.name: "info"
>   icon.width: 22
>   icon.height 22
> }
> ```
> 
> ^ at the moment this doesn't work because `icon` isn't actually object but maps to `StatusIcon.icon`. One of the reasons we've used QML's built-in `RoundButton` was because it exposes an entire `icon` object already with `name`, `source`, `width` and `height` properties.
> 
> With the latest implementation of this component we've kinda lost all of that because we've reimplemented it with a `Rectangle`.
> 
> 1. The design so far only uses a size of `32` for this kind of component. Unfortunately we can't hardcode `implicitWidth: 32` and `implicitHeight: 32` and then use `width` and `height` for icon sizes.. so the other option would be to introduce new properties accordingly:
> 
> ```
> StatusFlatRoundButton {
>   icon: "info"
>   iconWidth: 22
>   iconHeight 22
> }
> ```
> 
> @borismelnik thoughts?

i can introduce some icon settings like:
`icon.width icon.height` and etc.

Its okay for you?

**Comment by PascalPrecht** [comment]
That'd be awesome

**Comment by PascalPrecht** [comment]
@borismelnik FYI: https://github.com/status-im/StatusQ/pull/61 introduces `StatusIconSettings` that can be used for that.
