### ISSUE TITLE
Implement StatusInput cursor as per designs

### ISSUE THREAD

**Issue by alexandraB99** [status-im/StatusQ#578]
<img width="386" alt="in" src="https://user-images.githubusercontent.com/31625338/157893694-9267b495-4ea1-499a-8613-b4a8a28d056c.png">

**Comment by Khushboo-dev-cpp** [comment]
The cursor has already been implemented in desktop here https://github.com/status-im/status-desktop/pull/5088/files#diff-6c689de5e41330b124451072067a9e23f34d9daabbb76328ecdcd71e99c8e106.
Can be used for reference and would appreciate if someone removed it from the desktop file once it is added to StatusInput.

**Comment by igor-sirotin** [comment]
Do we have any designs on animation?

**Comment by PascalPrecht** [comment]
It's just blinking like native cursor behaviour
