### ISSUE TITLE
`StatusBaseInput` invalid border color

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/StatusQ#640]
After losing active focus `StatusBaseInput` changes it's the border color from `Theme.palette.primaryColor1` to `Theme.palette.primaryColor2` instead of switching to `transparent`.

The correct value can then be achived by "unhovering" mouse on the input.
![output](https://user-images.githubusercontent.com/25482501/166240347-99592a0b-df2c-45ff-be81-1367d3210c66.gif)

**Comment by PascalPrecht** [comment]
Thanks for reporting this!
