### ISSUE TITLE
Sandbox doesn't start in Release build

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/StatusQ#641]
```
17:35:06: Starting sandboxapp.exe...
("qrc:/src", "C:/Users/i.sirotin/Status/StatusQ/sandbox/bin", "qrc:/qt-project.org/imports", "C:/Qt/5.15.2/msvc2019_64/qml")
QQmlApplicationEngine failed to load component
qrc:/main.qml:401:13: DemoApp is not a type
```

**Comment by PascalPrecht** [comment]
Did you run the `scripts/build` script?

**Comment by igor-sirotin** [comment]
No, I just used Qt Creater to build the `sandbox.pro`.
It works ok in Debug mode, but failes in Release.

It seems to happen because in Debug mode the app loads qml files from disk, and from resources in Release mode. And not all files (including `DemoApp`) is added to resources. Adding those fixes the problem, but then more and more files are not found in the resources. 

I'm digging into this right now

**Comment by PascalPrecht** [comment]
Ah sweet! Feel free to send a PR in case you manage to fix it!
