### ISSUE TITLE
Add property in `StatusInput` to change the `StatusBaseInput` heigth to a custom one

### ISSUE THREAD

**Issue by noeliaSD** [status-im/StatusQ#753]
Add property to allow the consumer of `StatusInput` changing the `StatusBaseInput` heigth to a different height than the default one.

Once it is done, it is needed to update in desktop at least:
- Amount input:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A484670

**Comment by alexandraB99** [comment]
Could you please if this https://github.com/status-im/StatusQ/pull/794 fixes the issue?

**Comment by noeliaSD** [comment]
> Could you please if this #794 fixes the issue?

Yeah! By changing the `minimum / maximumHeight` and `topPadding / bottomPadding` it works as expected!
