### ISSUE TITLE
Merge StatusIconSettings, StatusImageSettings and StatusIconBackgroundSettings

### ISSUE THREAD

**Issue by alexandraB99** [status-im/StatusQ#781]
Update all components/places of usage

**Comment by PascalPrecht** [comment]
I think some further information would be useful here.
What are they being merged into? Is it going to be a new type? How do we handle cases where their APIs diverge?
For example while an `icon` can have a `name` and be loaded just using a name (this was done to align with QML's built-in `icon.name` properties) there's no such thing on an image (e.g. `image.name`) while there is soemthing like `image.source`.

Maybe we can lay out what the end product should/would look like and how this will affect existing APIs as this will be a major breaking change and should be done with good care.

**Comment by alexandraB99** [comment]
@PascalPrecht this is just an improvement we discussed in Rabbits, it doesn't make much sense to maintain this kind of complexity in this case (having 3 different types which are related and can be merged). So instead of  `StatusIconSettings`, `StatusImageSettings` and `StatusIconBackgroundSettings`
we only have `StatusAssetSettings` and have everything set there. Easier to understand, maintain and less lines of code.

**Comment by PascalPrecht** [comment]
Fair enough!
